#!/bin/bash

cat <<- _EOM_


Note that you must have tmux installed. 

_EOM_


echo "Killing any old Metronome tmux sessions."
tmux kill-session -t Metronome

echo "Launching New Session."
tmux new-session -d -s Metronome
tmux kill-session -t Metronome
tmux new-session -d -s Metronome

tmux new-window
tmux rename-window 'Redis server'
tmux send-keys 'redis-server' 'C-m'

tmux new-window
tmux send-keys 'echo y|./gethAttach' 'C-m'
tmux rename-window 'MET ETH'


tmux new-window
tmux send-keys 'echo y|./gethAttach --chain etc; touch launched' 'C-m'
tmux rename-window 'MET ETC'

echo "Waiting for parity ETH and ETC To launch."
while ! [ -f ./launched ]
do
  echo -n "#"
  sleep 1
done

tmux select-window -t='MET ETH'
tmux send-keys 'geth attach http://127.0.0.1:8545 --preload abi/eth/metronome.js' 'C-m'

tmux select-window -t='MET ETC'
tmux send-keys 'geth attach http://127.0.0.1:8555 --preload abi/etc/metronome.js' 'C-m'

tmux new-window
tmux rename-window 'Off-chain Validator'
tmux send-keys 'node index.js launch --dev' 'C-m'
# tmux send-keys 'node index.js launch --dev' 'C-m'  # 'metronome-validator launch' is actual command
tmux -2 attach-session -t Metronome

